// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsychologyApp.Controllers;

#nullable disable

namespace PsychologyApp.Migrations
{
    [DbContext(typeof(PsychologyAppContext))]
    [Migration("20250207174940_MentalDisorderCategoryAdd")]
    partial class MentalDisorderCategoryAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PsychologyApp.Models.MentalDisorder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PsychologyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PsychotherapyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTypeId");

                    b.HasIndex("PsychotherapyTypeId");

                    b.ToTable("MentalDisorders");
                });

            modelBuilder.Entity("PsychologyApp.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PsychologyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PsychotherapyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTypeId");

                    b.HasIndex("PsychotherapyTypeId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("PsychologyApp.Models.PsychologyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PsychologyTypes");
                });

            modelBuilder.Entity("PsychologyApp.Models.PsychotherapyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PsychotherapyTypes");
                });

            modelBuilder.Entity("PsychologyApp.Models.QuestionnaireAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PsychologyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PsychotherapyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTypeId");

                    b.HasIndex("PsychotherapyTypeId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionnaireAnswers");
                });

            modelBuilder.Entity("PsychologyApp.Models.QuestionnaireQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("QuestionnaireQuestions");
                });

            modelBuilder.Entity("PsychologyApp.Models.MentalDisorder", b =>
                {
                    b.HasOne("PsychologyApp.Models.PsychologyType", "PsychologyType")
                        .WithMany("MentalDisorders")
                        .HasForeignKey("PsychologyTypeId");

                    b.HasOne("PsychologyApp.Models.PsychotherapyType", "PsychotherapyType")
                        .WithMany("MentalDisorders")
                        .HasForeignKey("PsychotherapyTypeId");

                    b.Navigation("PsychologyType");

                    b.Navigation("PsychotherapyType");
                });

            modelBuilder.Entity("PsychologyApp.Models.Partner", b =>
                {
                    b.HasOne("PsychologyApp.Models.PsychologyType", "PsychologyType")
                        .WithMany()
                        .HasForeignKey("PsychologyTypeId");

                    b.HasOne("PsychologyApp.Models.PsychotherapyType", "PsychotherapyType")
                        .WithMany()
                        .HasForeignKey("PsychotherapyTypeId");

                    b.Navigation("PsychologyType");

                    b.Navigation("PsychotherapyType");
                });

            modelBuilder.Entity("PsychologyApp.Models.QuestionnaireAnswer", b =>
                {
                    b.HasOne("PsychologyApp.Models.PsychologyType", "PsychologyType")
                        .WithMany()
                        .HasForeignKey("PsychologyTypeId");

                    b.HasOne("PsychologyApp.Models.PsychotherapyType", "PsychotherapyType")
                        .WithMany()
                        .HasForeignKey("PsychotherapyTypeId");

                    b.HasOne("PsychologyApp.Models.QuestionnaireQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsychologyType");

                    b.Navigation("PsychotherapyType");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PsychologyApp.Models.PsychologyType", b =>
                {
                    b.Navigation("MentalDisorders");
                });

            modelBuilder.Entity("PsychologyApp.Models.PsychotherapyType", b =>
                {
                    b.Navigation("MentalDisorders");
                });

            modelBuilder.Entity("PsychologyApp.Models.QuestionnaireQuestion", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
